### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by Zanci19** [fnmwolf/Anaconda#1]
When trying to decompile the game to MFA, I get this error:
![image](https://user-images.githubusercontent.com/73758755/126898908-2ec006e5-9085-488d-bd6b-3b68a2b51439.png)

**Comment by fnmwolf** [comment]
Use this: https://cdn.discordapp.com/attachments/843916269090373642/868175742498930758/AnacondaDev_-_Compression.zip

**Comment by Zanci19** [comment]
Nope, still get the same error

**Comment by fnmwolf** [comment]
I pushed an update to the decompiler you can try, also try using for your command: C:\Python27\python.exe bimbam.py (your game exe)

also put a folder in your C drive called Out, your MFA will go there
