### ISSUE TITLE
done everything right but decompile.bat just doesn't get detected or something

### ISSUE THREAD

**Issue by DeceptedPar** [fnmwolf/Anaconda#10]
![image](https://user-images.githubusercontent.com/64243677/159062739-75cfd066-98df-48d6-93c9-55a88185d871.png)
I used install.bat and then used AnacondaGUI.py and tried to decompile ANYTHING and this, popped up...

**Comment by fnmwolf** [comment]
Do not use the GUI program.  Instead, open a cmd in the tools folder, and use the command: C:\python27\python.exe bimbam.py (your game exe location) (your output folder location - leave blank for C:\Out)

**Comment by AITYunivers** [comment]
First off you shouldn't be using the Python Terminal for anything
Second off you shouldn't be running AnacondaGUI.py
