### ISSUE TITLE
"MemoryError() in 'mmfparser.bytereader.ensure_size' ignored" -empty output

### ISSUE THREAD

**Issue by krumplivagyok** [fnmwolf/Anaconda#12]
When trying to decompile SL:

Anaconda Decompiler
ONLY for educational purpose, or game datamining ;)

(unknown chunk 8774)
(unknown chunk 8785)
creating new data transform
(unknown chunk 8783)
(unknown chunk 8781)
Exception MemoryError: MemoryError() in 'mmfparser.bytereader.ensure_size' ignored

**Comment by fnmwolf** [comment]
Your computer may not have enough RAM, or you are not using the 64-bit version of Python.
