### ISSUE TITLE
Is this actually safe?

### ISSUE THREAD

**Issue by ghost** [fnmwolf/Anaconda#15]
VirusTotal detects this as a virus. So I’m wondering if this actually is safe.

I think I will run this in an enclosed vm

**Comment by AITYunivers** [comment]
If you think it's a virus, don't use it. We shouldn't have to try to convince you that this project, which is open sourced, isn't a virus.

**Comment by ghost** [comment]
That didn’t help me but I guess I will try it

**Comment by ghost** [comment]
my computer is crashing!

**Comment by ghost** [comment]
trying to extract it

**Comment by ghost** [comment]
why did you tell me to install this virus

**Comment by ghost** [comment]
explorer.exe crashed

**Comment by ghost** [comment]
im trying again
