### ISSUE TITLE
struct.error: 1 bytes required (I know it is because of Anaconda not supporting Clickteam fusion 2.5+) 

### ISSUE THREAD

**Issue by wendellmeset** [fnmwolf/Anaconda#18]
Hey,
I was wondering if there is any way to decompile clickteam fusion 2.5+ games. I know there is some kind of private tool for doing so, but it would really help if a public tool/utility was released for this purpose. If not wanted, please tell me how to decompile clickteam fusion 2.5+ games.

**Comment by fnmwolf** [comment]
We have a new tool available at https://github.com/CTFAK/CTFAK2.0
