### ISSUE TITLE
Conversion Issues with MMF2 Game

### ISSUE THREAD

**Issue by g-l-i-t-c-h-o-r-s-e** [fnmwolf/Anaconda#22]
Heyo, I have a game here that has some minor animation issues, and doesn't build at all.
However if I delete the `Launcher` frame, it Builds on my Windows 10 desktop but with animation issues and missing .dll errors
[This](https://www.mediafire.com/file/euq6x1o3lykgb42/TEMNO.exe/file) is the game in question, its from around 2012-2013 if I recall
I had to use the CTF-Developer-2.5 Extension Manager to use the newer version of the waterSurface.mfx to open it properly
The same issues appear to occur in MMF2-Developer as well

The original filepaths in the .mfa are:
```
C:\Hra\Temno\Temno.mfa
C:\Hra\Temno\TEMNO.exe
C:\Hra\Temno\Data\Backgrounds\launcher.png
C:\Hra\Temno\Data\Objects\blurrtree1.png
C:\Hra\Temno\Data\Objects\blurrtree2.png
C:\Hra\Temno\Data\Backgrounds\Chapter1\01.png
C:\Hra\Temno\Data\Backgrounds\Chapter1\01_22.png
C:\Hra\Temno\Data\Objects\Cutscenes\01.wmv
C:\Hra\Temno\Data\Objects\Cutscenes\02.wmv
C:\Hra\Temno\Data\Objects\Cutscenes\03.wmv
```

**Comment by g-l-i-t-c-h-o-r-s-e** [comment]
This is the error I get if I build without deleting `Launcher` frame
![image](https://user-images.githubusercontent.com/17163949/221066449-dd21e7c2-b135-4f54-829e-7cd8ee1b4065.png)

This is the error I get if I build and open game, after deleting `Launcher` frame
![image](https://user-images.githubusercontent.com/17163949/221066514-0e992edb-18ed-4e87-ae6d-2f0608481eda.png)

**Comment by fnmwolf** [comment]
Make sure you set the frame transitions in the frame settings to some option other than "Transition"
