### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Moo-Moo-Armageddon** [fnmwolf/Anaconda#23]
I keep getting this error when I try to run Anaconda

```
line 17
    print 'Anaconda Decompiler'
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```

What's happening? Why is it doing this?

**Comment by fnmwolf** [comment]
Make sure to use Python 2.7 64-bit. The installer is included with your Anaconda download, for your convenience.
