### ISSUE TITLE
i dose not work AT ALL

### ISSUE THREAD

**Issue by BEATNINJA8447** [fnmwolf/Anaconda#24]
ive have downloaded the zip and extracted it run the exe as administrator selected the game and output file i click decompile and i says done! i go to the file and there is nothing there

**Comment by fnmwolf** [comment]
Create a folder in the root of your C Drive called Out, by default the files will be stored there. If it still doesn't work please upload a screenshot of the command window after it claims to have finished decompiling your game.

**Comment by BEATNINJA8447** [comment]
![image](https://user-images.githubusercontent.com/128325908/226459704-92f911b2-daf3-4644-a738-e9716fb21d09.png)

**Comment by BEATNINJA8447** [comment]
i press decompile it takes like 2 seconds says done and dosent work this also dosent work on my laptop either

**Comment by fnmwolf** [comment]
Use the command line tool instead of the GUI, the syntax is:
`C:\Python27\python.exe bimbam.py <your game exe path here> <your output folder here>`

**Comment by BEATNINJA8447** [comment]
![image](https://user-images.githubusercontent.com/128325908/226537017-fc3fbe32-775a-4fd9-8381-dd454c185c43.png)
do i need the <>?

**Comment by ChorusCory** [comment]
most likely, as the path names have spaces in them
