### ISSUE TITLE
struct.error: 1 bytes required

### ISSUE THREAD

**Issue by MrFriccern** [fnmwolf/Anaconda#26]
Yeah.. same problem with bimbam1 too.. idk tbh what to do
(using Win 7 virtual machine)
Game: Playtime with Percy
![Снимок экрана 2023-11-09 165801](https://github.com/fnmwolf/Anaconda/assets/85288660/a1c38922-0244-4e5d-b754-fdaf23be406a)

**Comment by fnmwolf** [comment]
The game you're trying to decompile is most likely a 2.5+ game and you'll need to use CTFAK instead.
