### ISSUE TITLE
It doesent decompile anything. (By that i mean FNaF 4)

### ISSUE THREAD

**Issue by TechGuy12774** [fnmwolf/Anaconda#4]

**Comment by fnmwolf** [comment]
What is the error message that it provides? Anaconda is capable of decompiling most, if not all Clickteam Fusion 2.5 games.

**Comment by TechGuy12774** [comment]
It doesen't give any errors it's just when it's done it just... it doesen't decompile it there's just nothing hower i did find this https://www.mediafire.com/view/eyfveq7lkx6lk7t/Screenshot_2021-12-21_160652.png/file

**Comment by fnmwolf** [comment]
Do not use the GUI tool. Instead open a command prompt in the tools folder. Use the following command: 

C:\Python27\python.exe bimbam.py (your game exe location)

make a folder in your C drive called Out and then run the command above

your MFA will go into the Out folder

**Comment by TechGuy12774** [comment]
I Went on vacation before i could do it or reply.

**Comment by TechGuy12774** [comment]
Also how do i open a cmd in the tools folder?

**Comment by fnmwolf** [comment]
I hope you enjoyed your vacation! To open a cmd in the tools folder, right click on the windows button and click on PowerShell, then type in cmd and push enter. Then type in cd (your anaconda tools folder location)

**Comment by TechGuy12774** [comment]
It don't work. https://www.mediafire.com/view/33eozoiu8371mpn/Screenshot_2021-12-30_161907.png/file

**Comment by fnmwolf** [comment]
You need to type in cd and the anaconda location (where bimbam.py is) in your downloads, not the location of Python itself.   Then use the command above to decompile - C:\Python27\python.exe bimbam.py (your game exe location)

**Comment by TechGuy12774** [comment]
I think it would make this easier if you just sent me a picture of you doing the proper command. I've literally try'd so many variations of doing this and none of them have worked. https://www.mediafire.com/view/4u8kdwraqpno23c/Screenshot_2022-01-01_083925.png/file

**Comment by TechGuy12774** [comment]
Oh and btw i'm not using Python Powershell i'm using the normal windows Powershell.

**Comment by fnmwolf** [comment]
![E72CD115-BFD4-4A39-9AE2-2312961F1C24](https://user-images.githubusercontent.com/81009031/147890567-7f6b32d8-ad68-43a5-b2c9-5fa37bd717dd.jpeg)

**Comment by fnmwolf** [comment]
Sorry for the bad quality pic, I don’t have access to my computer at the moment so I’m using a friends very old computer from like 10 years ago

**Comment by TechGuy12774** [comment]
Hello?

**Comment by TechGuy12774** [comment]
I ment a screenshot but i don't really care because i can read it and also it doesen't look low res.

**Comment by TechGuy12774** [comment]
Also btw You think that computer is bad? Well... MY COMPUTER IS SH*T!!! https://www.mediafire.com/view/7z2yxcpnxqn0jmy/Screenshot_2022-01-02_193032.png/file

**Comment by TechGuy12774** [comment]
Nevermind i have it.
