### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by approachcircle** [fnmwolf/Anaconda#5]
doesn't actually decompile anything, because the call to start "decompile.bat" isn't actually how you'd call to open a batch file using os.system(), so it just fails

**Comment by AITYunivers** [comment]
Then open the batch using command prompt, that is assuming you're using the AnacondaGUI.exe. I coded that a long time ago with 0 python experience, if you're having issues with it, just use the batch yourself.

I did start work on a C# GUI, and it works, I just never got around to polishing it.

**Comment by fnmwolf** [comment]
you can also just use the bimbam.py itself with syntax C:\Python27\python.exe bimbam.py (your game exe path) (your MFA output path - OPTIONAL - default is C:\Out if not specified)

**Comment by approachcircle** [comment]
just to confirm, i would have to download python 2.7 to run bimbam.py because of the fact that it uses python 2.7 syntax right?

**Comment by fnmwolf** [comment]
yeah, the python 2.7 installer is included with the repo download

**Comment by AITYunivers** [comment]
You can also use Install.bat to install all the required dependencies.

**Comment by approachcircle** [comment]
i ended up just calling bimbam.py directly, and using it to decompile an exe to an mfa. a couple of frames were pretty broken, but it worked for the most part which is fine

**Comment by AITYunivers** [comment]
@approachcircle If frames were broken might be because you don't have the proper extensions,, effects, dependencies, etc.

**Comment by approachcircle** [comment]
yeah probably, that would make sense @AITYunivers

**Comment by fnmwolf** [comment]
Just install the extensions that you’re missing and you should get a clean MFA with no bugs.  If you need further help send me the EXE you are decompiling and I will try it
