### ISSUE TITLE
Windows Defender detects as Malware

### ISSUE THREAD

**Issue by jessiejs** [fnmwolf/Anaconda#6]
The title is fairly self explanatory.
When you have Anaconda open, Windows Defender pesters you every 5 seconds.
This occurred on the latest release on GitHub.

**Comment by fnmwolf** [comment]
My new version was specifically designed not to trigger the false positive that windows defender gives (the file that sets it off is in the old 32-bit anaconda runtime, the 64-bit version doesn’t set it off, so I deleted the 32-bit version) and on my windows 11 computer it doesn’t set off AV

**Comment by AITYunivers** [comment]
@fnmwolf You REALLY need to delete the release in the releases tab.

@CodeLikeCrazE Don't use the release, download it via the source code. fnmwolf doesn't update the releases tab so it's over 7 months outdated.

**Comment by fnmwolf** [comment]
Yeah I know I have to update it.   Is there a way to have GitHub automatically do it for me? With the private CTFAK repo we have a GitHub Actions script to auto compile it but ClickNin wrote that and I have no idea how to do it for Python stuff, that project uses MSBuild for C# instead

**Comment by AITYunivers** [comment]
@fnmwolf Man no clue, the issue with that is we aren't compiling anything, the source code is how we ship it in general. The releases tab has the exact same thing as the source code. It's better off just deleting the Release then just mention something about it in the README.md
